### ISSUE TITLE
Set the search url from environment variables (for dev and production builds)

### ISSUE THREAD

**Issue by aih** [aih/SearchUSCode#22]
We would like to be able to vary some settings for dev and build, starting with the `serverName` url. We should maintain `environment.ts` files which are used in a build step `npm run build:dev` or `npm run build:prod` to change the settings.

**Comment by MichaelGlushkov** [comment]
i create two different scripts for build and start project with production environment. 
* npm run start:prod
*npm build:prod
change serverName yourself in environment.prod.ts, now both of them is localhost:8000/

**Comment by aih** [comment]
Working.
